# Generated by Django 4.1 on 2022-09-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_photo_remove_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productname',
            field=models.CharField(default=0, max_length=50, verbose_name='Mahsulot nomi'),
            preserve_default=False,
        ),
    ]
