# Generated by Django 4.1.1 on 2022-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sotuv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('summery', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
